# Generated by Django 5.2.8 on 2026-01-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0005_remove_group_members_group_admins_group_created_at_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='chema.GroupMembership', to='user.profile'),
        ),
    ]
