# Generated by Django 5.2.8 on 2026-02-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0006_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='external_wallet_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
