# Generated by Django 5.2.8 on 2026-02-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0007_group_external_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
