# Generated by Django 5.2.8 on 2026-02-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0008_alter_post_content'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='user.profile'),
        ),
    ]
