# Generated by Django 5.2.8 on 2026-02-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0010_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
