# Generated by Django 5.2.8 on 2025-11-29 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chema', '0002_initial'),
        ('condolence', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contributing_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deceased_contributions', to='user.profile'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_contributions', to='chema.group'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='group_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_contributions', to='user.profile'),
        ),
        migrations.AddField(
            model_name='deceased',
            name='deceased',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_deceased', to='user.profile'),
        ),
        migrations.AddField(
            model_name='deceased',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chema.group'),
        ),
        migrations.AddField(
            model_name='deceased',
            name='group_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='user.profile'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='deceased_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_deceased', to='condolence.deceased'),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('deceased_member', 'contributing_member')},
        ),
    ]
