# Generated by Django 5.2.8 on 2026-02-04 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condolence', '0002_initial'),
        ('user', '0001_initial'),
        ('wallet', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('wallet', 'Wallet Balance'), ('other', 'Other')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='contribution',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution', to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='deceased',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_for', to='user.profile'),
        ),
        migrations.AddField(
            model_name='deceased',
            name='funds_disbursed',
            field=models.BooleanField(default=False),
        ),
    ]
