# Generated by Django 5.2.8 on 2026-02-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOP_UP', 'Top-Up'), ('TRANSFER', 'Transfer to Group'), ('WITHDRAWAL', 'Withdrawal'), ('PAYOUT_RECEIVED', 'Payout Received')], max_length=20),
        ),
    ]
